### ISSUE TITLE
Factor of a number

### ISSUE THREAD

**Issue by parikshitsen** [parikshitsen/Python-#16]
In this Python Program, We will find the factorial of a number where the number should be entered by the user. Factorial of a number means multiply of all below number with each other till 1. If user enter 0 or 1 , then factorial of both numbers will be 1 only. Or If user enters negative numbers then it’s factorial is not defined.
For Example:
Number is 8.
8x7x6x5x4x3x2x1=40,320
Factorial of a 8 = 40,320
Note:-Factorial of n number is 1*2*3*…n. You will learn to calculate the factorial of a number using for loop in this example.

**Comment by rajatagarwalm** [comment]
plz assign me this
