### ISSUE TITLE
Find Second Smallest Element in an Array 

### ISSUE THREAD

**Issue by parikshitsen** [parikshitsen/Python-#19]
In this paragraph today we learn how to find second smallest element in an array with help of Python Programing concept.In Python it does not have arrays, but it has list with the help of using lists it is more easy and comfortable to work with in comparison to arrays.
For Example:
Input : list = [11, 15, 2, 4, 91, 10, 20, 16, 14]
Output :
Second Smallest element is: 4

**Comment by Ranimaheshwari** [comment]
please assign me this.
